// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1742971633);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1742971632);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{c7eaf8c3-b462-4c4b-8053-85671e2c9df1}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1742971622);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3f7769f0-295b-427a-87e3-49152e4d6b95}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1742971625);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1742971636295");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1742993236295");
user_pref("browser.search.region", "VN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1742971627");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230309232128");
user_pref("browser.startup.homepage_override.mstone", "111.0");
user_pref("browser.startup.lastColdStartupCheck", 1742971623);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "111.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "VN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "d0af6fbf197c4e049c17b0b18be98f5d");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230309232128");
user_pref("extensions.lastAppVersion", "111.0");
user_pref("extensions.lastPlatformVersion", "111.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"84c9ddba-3986-4ec5-b0fb-f70d2b912791\",\"pictureinpicture@mozilla.org\":\"db60c905-97ab-4e34-af86-d8c684e05fe3\",\"screenshots@mozilla.org\":\"d0e0b68a-e9c7-43a0-995d-6e2c53e691a5\",\"webcompat-reporter@mozilla.org\":\"674bb111-16f7-4fc7-a789-fb34ea7b4827\",\"webcompat@mozilla.org\":\"17dd2a91-cd85-43f7-b938-770fc567c4f1\",\"default-theme@mozilla.org\":\"a3dfbf9b-6a3f-42d4-b59d-b944beeb8889\",\"addons-search-detection@mozilla.com\":\"0bccbb32-7933-41d5-a332-408504fb094b\",\"google@search.mozilla.org\":\"11311db6-dc31-484b-b3ef-edbf524a2d9b\",\"amazondotcom@search.mozilla.org\":\"fb309097-cb4b-46fc-aa52-b7d242db5c3a\",\"wikipedia@search.mozilla.org\":\"697c4b2f-a853-4868-81d6-c5e7896a7721\",\"bing@search.mozilla.org\":\"e5305a0b-b425-4994-ba48-00cd62cb3a2b\",\"ddg@search.mozilla.org\":\"fce0cb79-88df-48fa-8be1-70a5d1551f83\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "10dd1bc2-c673-4eac-976e-d6abab7119cd");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1742971619);
user_pref("toolkit.telemetry.cachedClientID", "c4ba201d-6ded-4a19-9f77-9a10bb77ccb2");
user_pref("toolkit.telemetry.previousBuildID", "20230309232128");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
